name: CI/CD para AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Compactar lambda_function.py
        run: zip -j lambda_function.zip lambda_function.py

      - name: Fazer deploy para AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name RemovePDFPassword \
            --zip-file fileb://lambda_function.zip
